### ISSUE TITLE
Can we use pretrained model weights from seisbench to reproduce the results in this repo?

### ISSUE THREAD

**Issue by liutianlin0121** [seisbench/pick-benchmark#11]
Hi!

Thank you for this awesome repository! I have a question regarding the relationship between (i) the model weights trained using train.py in this repository and (ii) the pretrained model weights provided by the [SeisBench](https://github.com/seisbench/seisbench) repository. Are they equivalent?

More specifically, I'm interested in reproducing the results in your paper. According to the README file in this repo, one approach is to use PyTorch Lightning and train models on all datasets. However, I understand that the SeisBench repository already provides pretrained models on these datasets, which, if I'm correct, are models trained on the pick-benchmark. Does this mean we could download the pretrained model from SeisBench and then use the correct target files provided here to reproduce the experimental results?

Thank you!

**Comment by yetinam** [comment]
Hi @liutianlin0121 ,

sorry, i somehow missed your question here. As you correctly state, the weights in SeisBench are the exact weights that we obtained with the training scripts in this repository. However, in terms of format they're not fully identical. The evaluation script loads a PyTorch Lightning checkpoint while the model weight in SeisBench are in PyTorch format (extracted from these checkpoints). Therefore, you won't be able to use the evaluation script as is. However, it should be pretty straightforward to modify the setup of the model in the evaluation to load the weights from SeisBench instead of from a checkpoint.

**Comment by liutianlin0121** [comment]
Thanks so much!
