### ISSUE TITLE
Question about model evaluation

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/pick-benchmark#8]
Thank you for providing the seisbench package. I've learned a lot after reading the code, but there are many details I haven't understood.

1. For task 2 and task 3, how do you guarantee only one phase exists in a 10s window?

2. Instead of dividing the testing into 3 tasks, if I want to simply calculate metrics in the following way:
- _True positive_: if the difference between the predicted pick and the reference pick is less than 0.1 s
- _False positive_: if (a) the distance between the predicted pick and the reference pick is greater than 0.1 s, or (b) there is a predicted pick, but no reference pick.
- _True negative_: there are no reference picks and predicted picks.
- _False negative_: there are reference picks but no positive prediction.

what should I do with the code?

Maybe I should modify `predict_step` functions in `models.py`, but I feel lost here.
https://github.com/seisbench/pick-benchmark/blob/31057a1981f6cd50f828fbf8c284c2b0a228a502/benchmark/models.py#L197-L220
Why is `local_pred = pred[i, :, start_sample:end_sample]` needed in line 210?

Since a SteeredWindow has been added to the generator
https://github.com/seisbench/pick-benchmark/blob/31057a1981f6cd50f828fbf8c284c2b0a228a502/benchmark/eval.py#L125-L126
isn't the `x` automatically trimmed to `start_sample:end_sample` by the SteeredWindow?

Can I delete the lines following `pred = self.model(x) `, and finaly `return pred`?  

How can I turn `pred` to picks? Do I need to first store the `pred` array in obspy.Stream, and then use the `classify` or `pick_from_annotation`  functions in the model api?

**Comment by yetinam** [comment]
Hey @zhong-yy,

thanks for your questions.

1. This happens when generating the targets. Check these lines [here](https://github.com/seisbench/pick-benchmark/blob/31057a1981f6cd50f828fbf8c284c2b0a228a502/benchmark/generate_eval_targets.py#L215). We check for every pick if it can be isolated. Note that there might still be two picks in a window, if one of them is not annotated in the dataset.
2. You're correct, the best place to do this is to modify the predict step. The key question is, what information you need to calculate your metric. As far as I see, you'll the confidence value, i.e., the highest predicted confidence to select if something is a detection, and the time of this peak.

If you want to return the full probability curves instead, just directly use `return pred` as you suggested. However, that might take a lot of storage, so I'd usually not recommend it. To get from probability curves to picks, you need to decide on a strategy. Usually, I would suggest running some sort of trigger. If you only want to select at most one pick per window, I'd just use the sample with highest probability.

Lastly, why do we need `local_pred = pred[i, :, start_sample:end_sample]` even though there's a SteeredWindow? The targets define a window length, however, the model might need a different window length as input. This is because, different models have different numbers of input samples but for comparability we need to use the same targets. Therefore, steered window returns a window of the rights size for the model and indicates which samples are the defined target window (`start_sample:end_sample`). The model then predicts using the full window but ignores all predictions outside the target window.

Hope that helped answering your question!

**Comment by zhong-yy** [comment]
Thank you very much for your answers and advice. 

Now I understand why using `pred[i, :, start_sample:end_sample]`. It is also noteworthy that the `start_sample` and `end_sample` in `window_border`  are indices for the trimmed window instead of the original window.

For selection of picks, using the sample with the highest probability may be the easiest way. However, even though there is only one labelled pick within the window, we cannot guarantee there are no other picks that haven't been labelled. Then   the labelled pick may has the second highest probability. In this case if we only choose the highest probability, we would incorrectly mark this trace as a false negative or assign it a high residual.

On the other hand, if we use some sort of trigger to get multiple picks, the shape of output will be different for each trace and each batch.
